import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to{" "}
          <a href="https://www.npmjs.com/package/4rest">Vainer's Project!</a>
        </h1>

        <p className={styles.description}>Shittiest Project Ever Made.</p>

        <div className={styles.grid}>
          <a href="https://github.com/LiorVainer/4rest" className={styles.card}>
            <h2>Github &rarr;</h2>
            <p>See 4rest in Github!</p>
          </a>

          <a href="https://www.npmjs.com/package/4rest" className={styles.card}>
            <h2>NPM &rarr;</h2>
            <p>See 4rest in NPM!</p>
          </a>
        </div>
      </main>
    </div>
  );
};

export default Home;
